### ISSUE TITLE
`copy below url to Additional Boards Manager URLs` 

### ISSUE THREAD

**Issue by tschrama** [Seeed-Studio/ArduinoCore-imxrt#3]
`copy below url to Additional Boards Manager URLs` 

doesnt work but gives theres error messages:

Index error: could not find referenced tool name=riscv64-unknown-elf-gcc version=8.2.0 packager=Seeeduino
Index error: could not find referenced tool name=kflash version=1.3.0 packager=Seeeduino
Index error: could not find referenced tool name=kendryte-standalone-sdk version=0.5.6 packager=Seeeduino
Index error: could not find referenced tool name=riscv64-unknown-elf-gcc version=8.2.0 packager=Seeeduino
Index error: could not find referenced tool name=kflash version=1.3.0 packager=Seeeduino
Index error: could not find referenced tool name=kendryte-standalone-sdk version=0.5.6 packager=Seeeduino

**Comment by LynnL4** [comment]
Hi, it seems to be issuse of https://github.com/Seeed-Studio/ArduinoCore-k210/issues/13
